CREATE DATABASE DISAFRA;
USE DISAFRA;
CREATE TABLE PERSONA(
	ID_PERSONA INT NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(50) NOT NULL,
	APELLIDO VARCHAR(50) NOT  NULL,
	FECHA_NACIMIENTO DATE NOT NULL,
	EDAD INT NOT NULL,
	PRIMARY KEY(ID_PERSONA)
)ENGINE=InnoDB;

CREATE TABLE TIPO_TELEFONO(
	ID_TIPO_TELEFONO INT NOT NULL AUTO_INCREMENT,
	TIPO VARCHAR(15),
	PRIMARY KEY(ID_TIPO_TELEFONO)
)ENGINE=InnoDB;

CREATE TABLE TELEFONO(
	ID_TELEFONO INT NOT NULL AUTO_INCREMENT,
	NUMERO VARCHAR(16) NOT NULL,
	TIPO_TELEFONO_ID INT NOT NULL,
	EXTENSION VARCHAR(5) NULL,
	PERSONA_ID INT NOT NULL,
	PRIMARY KEY(ID_TELEFONO),
	FOREIGN KEY(TIPO_TELEFONO_ID) REFERENCES TIPO_TELEFONO(ID_TIPO_TELEFONO)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
	FOREIGN KEY(PERSONA_ID) REFERENCES PERSONA(ID_PERSONA)
	ON UPDATE CASCADE
	ON DELETE CASCADE
)ENGINE=InnoDB;

CREATE TABLE DEPARTAMENTO(
	ID_DEPARTAMENTO INT NOT NULL AUTO_INCREMENT,
	DEPARTAMENTO VARCHAR(25),
	PRIMARY KEY(ID_DEPARTAMENTO)
)ENGINE=InnoDB;

CREATE TABLE MUNICIPIO(
	ID_MUNICIPIO INT NOT NULL AUTO_INCREMENT,
	MUNICIPIO VARCHAR(35) NOT NULL,
	DEPARTAMENTO_ID INT NOT NULL,
	PRIMARY KEY(ID_MUNICIPIO),
	FOREIGN KEY(DEPARTAMENTO_ID) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO)
	ON UPDATE CASCADE
	ON DELETE CASCADE
)ENGINE=InnoDB;

CREATE TABLE DIRECCION(
	ID_DIRECCION INT NOT NULL AUTO_INCREMENT,
	DIRECCION VARCHAR(150) NOT NULL,
	REFERENCIA VARCHAR(150) NULL,
	MUNICIPIO_ID INT NOT NULL,
	PERSONA_ID INT NOT NULL,
	PRIMARY KEY(ID_DIRECCION),
	FOREIGN KEY(MUNICIPIO_ID) REFERENCES MUNICIPIO(ID_MUNICIPIO)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
	FOREIGN KEY(PERSONA_ID) REFERENCES PERSONA(ID_PERSONA)
	ON UPDATE CASCADE
	ON DELETE CASCADE
)ENGINE=InnoDB;

CREATE TABLE USUARIO_CLIENTE(
	CORREO VARCHAR(100) NOT NULL,
	PASS VARCHAR(64) NOT NULL,
	ACTIVO CHAR(1) NOT NULL,
	FECHA_CREADO DATE,
	PRIMARY KEY(CORREO)
)ENGINE=InnoDB;

CREATE TABLE CLIENTE(
	NIT_CLIENTE VARCHAR(15) NOT NULL,
	PERSONA_ID INT NOT NULL,
	MAYORISTA CHAR(1) NOT NULL,
	CORREO VARCHAR(100) NOT NULL,
	PRIMARY KEY(NIT_CLIENTE),
	FOREIGN KEY(CORREO) REFERENCES USUARIO_CLIENTE(CORREO)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
    FOREIGN KEY(PERSONA_ID) REFERENCES PERSONA(ID_PERSONA)
    ON UPDATE CASCADE
    ON DELETE CASCADE
)ENGINE=InnoDB;

CREATE TABLE PUESTO(
	ID_PUESTO INT NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(50) NOT NULL,
	REQUISITOS VARCHAR(255) NULL,
	DESCRIPCION VARCHAR(255) NULL,
	SALARIO DECIMAL(7,2) NOT NULL,
	HORARIO_ENTRADA TIME NOT NULL,
	HORARIO_SALIDA TIME NOT NULL,
	PRIMARY KEY(ID_PUESTO)
)ENGINE=InnoDB;

CREATE TABLE EMPLEADO(
	COD_EMPLEADO INT NOT NULL AUTO_INCREMENT,
	PASS VARCHAR(64) NOT NULL,
	PERSONA_ID INT NOT NULL,
	CORREO VARCHAR(100) NULL,
	PUESTO_ID INT NOT NULL,
	PRIMARY KEY(COD_EMPLEADO),
	FOREIGN KEY(PERSONA_ID) REFERENCES PERSONA(ID_PERSONA)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
	FOREIGN KEY(PUESTO_ID) REFERENCES PUESTO(ID_PUESTO)
	ON UPDATE CASCADE
	ON DELETE CASCADE
)ENGINE=InnoDB;

CREATE TABLE SUCURSAL(
	ID_SUCURSAL INT NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(35) NOT NULL,
	CORREO VARCHAR(100) NOT NULL,
	DIRECCION_ID INT NOT NULL,
	TELEFONO_ID INT NOT NULL,
	PRIMARY KEY(ID_SUCURSAL),
	FOREIGN KEY(DIRECCION_ID) REFERENCES DIRECCION(ID_DIRECCION)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
	FOREIGN KEY(TELEFONO_ID) REFERENCES TELEFONO(ID_TELEFONO)
	ON UPDATE CASCADE
	ON DELETE CASCADE
)ENGINE=InnoDB;

CREATE TABLE USUARIO_SUCURSAL(
	USUARIO VARCHAR(50),
	PASS VARCHAR(64) NOT NULL,
	ACTIVO CHAR(1) NOT NULL,
	FECHA_CREADO DATE,
	SUCURSAL_ID INT NOT NULL,
	PRIMARY KEY(USUARIO),
	FOREIGN KEY(SUCURSAL_ID) REFERENCES SUCURSAL(ID_SUCURSAL)
	ON UPDATE CASCADE
	ON DELETE CASCADE
)ENGINE=InnoDB;

CREATE TABLE PROVEEDOR(
	ID_PROVEEDOR INT NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(35) NOT NULL,
	CORREO VARCHAR(100) NOT NULL,
	DIRECCION_ID INT NOT NULL,
	TELEFONO_ID INT NOT NULL,
	PRIMARY KEY(ID_PROVEEDOR),
	FOREIGN KEY(DIRECCION_ID) REFERENCES DIRECCION(ID_DIRECCION)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
	FOREIGN KEY(TELEFONO_ID) REFERENCES TELEFONO(ID_TELEFONO)
	ON UPDATE CASCADE
	ON DELETE CASCADE
)ENGINE=InnoDB;

CREATE TABLE VISITADOR(
	ID_VISITADOR INT NOT NULL AUTO_INCREMENT,
	PERSONA_ID INT NOT NULL,
	PROVEEDOR_ID INT NOT NULL,
	PRIMARY KEY(ID_VISITADOR),
	FOREIGN KEY(PERSONA_ID) REFERENCES PERSONA(ID_PERSONA)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
	FOREIGN KEY(PROVEEDOR_ID) REFERENCES PROVEEDOR(ID_PROVEEDOR)
	ON UPDATE CASCADE
	ON DELETE CASCADE
)ENGINE=InnoDB;

CREATE TABLE MARCA(
	ID_MARCA INT NOT NULL AUTO_INCREMENT,
	MARCA VARCHAR(35) NOT NULL,
	PRIMARY KEY(ID_MARCA)
)ENGINE=InnoDB;

CREATE TABLE PRODUCTO(
	COD_PRODUCTO VARCHAR(25) NOT NULL,
	NOMBRE VARCHAR(35) NOT NULL,
	DESCRIPCION VARCHAR(255) NULL,
	PORCENTAJE_GANANCIA DECIMAL(4,2) NOT NULL,
	PRECIO_VENTA DECIMAL(7,2) NOT NULL,
	FECHA_AGREGADO DATE NOT NULL,
	FECHA_VENCIMIENTO DATE NOT NULL,
	RECIEN_INGRESO CHAR(1) NOT NULL,
	CANTIDAD INT NOT NULL,
	MARCA_ID INT NOT NULL,
	SUCURSAL_ID INT NOT NULL,
	PRIMARY KEY(COD_PRODUCTO),
	FOREIGN KEY(MARCA_ID) REFERENCES MARCA(ID_MARCA)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
	FOREIGN KEY(SUCURSAL_ID) REFERENCES SUCURSAL(ID_SUCURSAL)
	ON UPDATE CASCADE
	ON DELETE CASCADE
)ENGINE=InnoDB;

CREATE TABLE CATEGORIA(
	ID_CATEGORIA INT NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(35) NOT NULL,
	DESCRIPCION VARCHAR(255) NULL,
	PRIMARY KEY(ID_CATEGORIA)
)ENGINE=InnoDB;

CREATE TABLE SUB_CATEGORIA(
	ID_SUB_CATEGORIA INT NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(35) NOT NULL,
	CATEGORIA_ID INT NOT NULL,
	PRODUCTO_COD VARCHAR(25) NOT NULL,
	PRIMARY KEY(ID_SUB_CATEGORIA),
	FOREIGN KEY(CATEGORIA_ID) REFERENCES CATEGORIA(ID_CATEGORIA)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
	FOREIGN KEY(PRODUCTO_COD) REFERENCES PRODUCTO(COD_PRODUCTO)
	ON UPDATE CASCADE
	ON DELETE CASCADE
)ENGINE=InnoDB;

CREATE TABLE DETALLE_PRODUCTO(
	ID_DETALLE_PRODUCTO INT NOT NULL AUTO_INCREMENT,
	PROVEEDOR_ID INT NOT NULL,
	PRODUCTO_COD VARCHAR(25) NOT NULL,
	PRECIO_COSTO DECIMAL(7,2) NOT NULL,
	PRIMARY KEY(ID_DETALLE_PRODUCTO),
	FOREIGN KEY(PROVEEDOR_ID) REFERENCES PROVEEDOR(ID_PROVEEDOR)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
	FOREIGN KEY(PRODUCTO_COD) REFERENCES PRODUCTO(COD_PRODUCTO)
	ON UPDATE CASCADE
	ON DELETE CASCADE
)ENGINE=InnoDB;

CREATE TABLE COMPRA(
	NUM_COMPRA INT NOT NULL AUTO_INCREMENT,
	DESCRIPCION VARCHAR(255) NULL,
	TOTAL DECIMAL(7,2) NOT NULL,
	TOTAL_PAGADO DECIMAL(7,2) NOT NULL,
	PAGADO CHAR(1) NOT NULL,
	FECHA_COMPRA DATE NOT NULL,
	ENTREGADO CHAR(1) NOT NULL,
	FECHA_ENTREGADO DATE NOT NULL,
	VISITADOR_ID INT NOT NULL,
	EMPLEADO_COD INT NOT NULL,
	PRIMARY KEY(NUM_COMPRA),
	FOREIGN KEY(VISITADOR_ID) REFERENCES VISITADOR(ID_VISITADOR)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
	FOREIGN KEY(EMPLEADO_COD) REFERENCES EMPLEADO(COD_EMPLEADO)
	ON UPDATE CASCADE
	ON DELETE CASCADE
)ENGINE=InnoDB;

CREATE TABLE DETALLE_COMPRA(
	ID_DETALLE_COMPRA INT NOT NULL AUTO_INCREMENT,
	DETALLE_PRODUCTO_ID INT NOT NULL,
	CANTIDAD INT NOT NULL,
	SUBTOTAL DECIMAL(7,2) NOT NULL,
	COMPRA_NUM INT NOT NULL,
	PRIMARY KEY(ID_DETALLE_COMPRA),
	FOREIGN KEY(DETALLE_PRODUCTO_ID) REFERENCES DETALLE_PRODUCTO(ID_DETALLE_PRODUCTO)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
	FOREIGN KEY(COMPRA_NUM) REFERENCES COMPRA(NUM_COMPRA)
	ON UPDATE CASCADE
	ON DELETE CASCADE
)ENGINE=InnoDB;

CREATE TABLE PAGO_COMPRA(
	NUM_PAGO INT NOT NULL,
	DESCRIPCION VARCHAR(255) NULL,
	FECHA_PAGO DATE NOT NULL,
	CANTIDAD_PAGADA DECIMAL(7,2) NOT NULL,
	EMPLEADO_COD INT NOT NULL,
	PRIMARY KEY(NUM_PAGO),
	FOREIGN KEY(EMPLEADO_COD) REFERENCES EMPLEADO(COD_EMPLEADO)
	ON UPDATE CASCADE
	ON DELETE CASCADE
)ENGINE=InnoDB;

CREATE TABLE VENTA(
	NUM_VENTA INT NOT NULL AUTO_INCREMENT,
	CLIENTE_NIT VARCHAR(15) NOT NULL,
	EMPLEADO_COD INT NOT NULL,
	SUCURSAL_ID INT NOT NULL,
	FECHA_VENTA DATE NOT NULL,
	TOTAL DECIMAL(7,2) NOT NULL,
	PRIMARY KEY(NUM_VENTA),
    FOREIGN KEY(CLIENTE_NIT) REFERENCES CLIENTE(NIT_CLIENTE)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
    FOREIGN KEY(EMPLEADO_COD) REFERENCES EMPLEADO(COD_EMPLEADO)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
    FOREIGN KEY(SUCURSAL_ID) REFERENCES SUCURSAL(ID_SUCURSAL)
    ON UPDATE CASCADE
    ON DELETE CASCADE
)ENGINE=InnoDB;

CREATE TABLE DESCUENTO(
	COD_DESCUENTO VARCHAR(25) NOT NULL,
	PORCENTAJE DECIMAL(4,2) NOT NULL,
	DESCRIPCION VARCHAR(255) NULL,
	PRIMARY KEY(COD_DESCUENTO)
)ENGINE=InnoDB;

CREATE TABLE DETALLE_VENTA(
	ID_DETALLE_VENTA INT NOT NULL AUTO_INCREMENT,
	PRODUCTO_COD VARCHAR(25) NULL,
	VENTA_NUM INT NOT NULL,
	DESCUENTO_COD VARCHAR(25) NULL,
	CANTIDAD INT NOT NULL,
	SUBTOTAL DECIMAL(7,2) NOT NULL,
	PRIMARY KEY(ID_DETALLE_VENTA),
    FOREIGN KEY(PRODUCTO_COD) REFERENCES PRODUCTO(COD_PRODUCTO)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
    FOREIGN KEY(VENTA_NUM) REFERENCES VENTA(NUM_VENTA)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
    FOREIGN KEY(DESCUENTO_COD) REFERENCES DESCUENTO(COD_DESCUENTO)
    ON UPDATE CASCADE
    ON DELETE CASCADE
)ENGINE=InnoDB;

CREATE TABLE COTIZACION(
	NUM_COTIZACION INT NOT NULL AUTO_INCREMENT,
	CLIENTE_NIT VARCHAR(15) NOT NULL,
	EMPLEADO_COD INT NOT NULL,
	SUCURSAL_ID INT NOT NULL,
	FECHA_VENTA DATE NOT NULL,
	TOTAL DECIMAL(7,2) NOT NULL,
	PRIMARY KEY(NUM_COTIZACION),
    FOREIGN KEY(CLIENTE_NIT) REFERENCES CLIENTE(NIT_CLIENTE)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
    FOREIGN KEY(EMPLEADO_COD) REFERENCES EMPLEADO(COD_EMPLEADO)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
    FOREIGN KEY(SUCURSAL_ID) REFERENCES SUCURSAL(ID_SUCURSAL)
    ON UPDATE CASCADE
    ON DELETE CASCADE
)ENGINE=InnoDB;

CREATE TABLE DETALLE_COTIZACION(
	ID_DETALLE_COTIZACION INT NOT NULL AUTO_INCREMENT,
	PRODUCTO_COD VARCHAR(25) NULL,
	COTIZACION_NUM INT NOT NULL,
	DESCUENTO_COD VARCHAR(25) NULL,
	CANTIDAD INT NOT NULL,
	SUBTOTAL DECIMAL(7,2) NOT NULL,
	PRIMARY KEY(ID_DETALLE_COTIZACION),
    FOREIGN KEY(PRODUCTO_COD) REFERENCES PRODUCTO(COD_PRODUCTO)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
    FOREIGN KEY(COTIZACION_NUM) REFERENCES COTIZACION(NUM_COTIZACION)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
    FOREIGN KEY(DESCUENTO_COD) REFERENCES DESCUENTO(COD_DESCUENTO)
    ON UPDATE CASCADE
    ON DELETE CASCADE
)ENGINE=InnoDB;