from django.contrib import admin
from .models import *

admin.site.register(Persona)
admin.site.register(Sucursal)
admin.site.register(Categoria)
admin.site.register(Marca)
admin.site.register(Descuento)
admin.site.register(Proveedor)
admin.site.register(Cliente)
admin.site.register(Empleado)
admin.site.register(Visitador)
admin.site.register(Venta)
admin.site.register(Producto)
admin.site.register(DetalleVenta)
admin.site.register(DetalleProducto)
admin.site.register(Compra)
admin.site.register(PagoCompra)
admin.site.register(DetalleCompra)
admin.site.register(Cotizacion)
admin.site.register(DetalleCotizacion)
admin.site.register(SubCategoria)
admin.site.register(Departamento)
admin.site.register(Municipio)
admin.site.register(Direccion)
admin.site.register(Puesto)
admin.site.register(Telefono)
admin.site.register(TipoTelefono)
admin.site.register(UsuarioCliente)
admin.site.register(UsuarioSucursal)